# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lyrics_client.api.lyrics_extraction_api import LyricsExtractionApi  # noqa: E501


class TestLyricsExtractionApi(unittest.TestCase):
    """LyricsExtractionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LyricsExtractionApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_extract_lyrics_extract_lyrics_post(self) -> None:
        """Test case for extract_lyrics_extract_lyrics_post

        Extract plain lyrics  # noqa: E501
        """
        pass

    def test_extract_lyrics_with_timestamps_extract_lyrics_with_timestamps_post(self) -> None:
        """Test case for extract_lyrics_with_timestamps_extract_lyrics_with_timestamps_post

        Extract lyrics with timestamps  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
