# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lyrics_client.models.chunk import Chunk  # noqa: E501

class TestChunk(unittest.TestCase):
    """Chunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Chunk:
        """Test Chunk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Chunk`
        """
        model = Chunk()  # noqa: E501
        if include_optional:
            return Chunk(
                start = 0.0,
                end = 12.92,
                text = 'Wake up in the mornin' feelin' like P. Diddy'
            )
        else:
            return Chunk(
                start = 0.0,
                end = 12.92,
                text = 'Wake up in the mornin' feelin' like P. Diddy',
        )
        """

    def testChunk(self):
        """Test Chunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
