# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lyrics_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_openapi_yaml_openapi_yaml_get(self) -> None:
        """Test case for get_openapi_yaml_openapi_yaml_get

        Get Openapi Yaml  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
