# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lyrics_client.models.lyrics_extraction_response import LyricsExtractionResponse  # noqa: E501

class TestLyricsExtractionResponse(unittest.TestCase):
    """LyricsExtractionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LyricsExtractionResponse:
        """Test LyricsExtractionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LyricsExtractionResponse`
        """
        model = LyricsExtractionResponse()  # noqa: E501
        if include_optional:
            return LyricsExtractionResponse(
                text = 'Never gonna give you up
Never gonna let you down',
                filename = '',
                duration_seconds = 1.337,
                sample_rate = 16000
            )
        else:
            return LyricsExtractionResponse(
                text = 'Never gonna give you up
Never gonna let you down',
                sample_rate = 16000,
        )
        """

    def testLyricsExtractionResponse(self):
        """Test LyricsExtractionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
