# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lyrics_client.models.lyrics_with_timestamps_response import LyricsWithTimestampsResponse  # noqa: E501

class TestLyricsWithTimestampsResponse(unittest.TestCase):
    """LyricsWithTimestampsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LyricsWithTimestampsResponse:
        """Test LyricsWithTimestampsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LyricsWithTimestampsResponse`
        """
        model = LyricsWithTimestampsResponse()  # noqa: E501
        if include_optional:
            return LyricsWithTimestampsResponse(
                text = 'Never gonna give you up...',
                chunks = [{end=3.5, start=0.0, text=Never gonna give you up}, {end=7.0, start=3.5, text=Never gonna let you down}],
                filename = '',
                total_duration_seconds = 1.337,
                sample_rate = 16000
            )
        else:
            return LyricsWithTimestampsResponse(
                text = 'Never gonna give you up...',
                chunks = [{end=3.5, start=0.0, text=Never gonna give you up}, {end=7.0, start=3.5, text=Never gonna let you down}],
                sample_rate = 16000,
        )
        """

    def testLyricsWithTimestampsResponse(self):
        """Test LyricsWithTimestampsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
