# coding: utf-8

# flake8: noqa

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "LyricsExtractionApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Chunk",
    "ErrorResponse",
    "HTTPValidationError",
    "LocationInner",
    "LyricsExtractionResponse",
    "LyricsWithTimestampsResponse",
    "ValidationError",
]

# import apis into sdk package
from lyrics_client.api.health_api import HealthApi as HealthApi
from lyrics_client.api.lyrics_extraction_api import LyricsExtractionApi as LyricsExtractionApi
from lyrics_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from lyrics_client.api_response import ApiResponse as ApiResponse
from lyrics_client.api_client import ApiClient as ApiClient
from lyrics_client.configuration import Configuration as Configuration
from lyrics_client.exceptions import OpenApiException as OpenApiException
from lyrics_client.exceptions import ApiTypeError as ApiTypeError
from lyrics_client.exceptions import ApiValueError as ApiValueError
from lyrics_client.exceptions import ApiKeyError as ApiKeyError
from lyrics_client.exceptions import ApiAttributeError as ApiAttributeError
from lyrics_client.exceptions import ApiException as ApiException

# import models into sdk package
from lyrics_client.models.chunk import Chunk as Chunk
from lyrics_client.models.error_response import ErrorResponse as ErrorResponse
from lyrics_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from lyrics_client.models.location_inner import LocationInner as LocationInner
from lyrics_client.models.lyrics_extraction_response import LyricsExtractionResponse as LyricsExtractionResponse
from lyrics_client.models.lyrics_with_timestamps_response import LyricsWithTimestampsResponse as LyricsWithTimestampsResponse
from lyrics_client.models.validation_error import ValidationError as ValidationError

