{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "karaoke-inator.labels" . | nindent 4 }}
    app: orchestrator
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.orchestrator.port }}
      targetPort: {{ .Values.orchestrator.port }}
      protocol: TCP
      name: api
  selector:
    app: orchestrator
{{- end }}
