# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401

from pydantic import validate_arguments

from typing_extensions import Annotated
from pydantic import Field, StrictStr

from typing import List, Optional

from song_management_client.models.lyrics_create import LyricsCreate
from song_management_client.models.lyrics_response import LyricsResponse
from song_management_client.models.lyrics_search_response import LyricsSearchResponse
from song_management_client.models.lyrics_update import LyricsUpdate

from song_management_client.api_client import ApiClient
from song_management_client.api_response import ApiResponse
from song_management_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class LyricsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def create_lyrics_lyrics_post(self, lyrics_create : LyricsCreate, vocal_file_path : Optional[StrictStr] = None, accompaniment_file_path : Optional[StrictStr] = None, **kwargs) -> LyricsResponse:  # noqa: E501
        """Create Lyrics  # noqa: E501

        Create a new lyrics entry with optional vocal and accompaniment audio files.  Accepts multipart/form-data. Text fields are form fields; files are uploaded to MinIO. Files are stored with deterministic paths based on the lyrics ID.  - vocal_file: Optional vocal track audio file (e.g., MP3, WAV) - accompaniment_file: Optional accompaniment/ instrumental track  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_lyrics_lyrics_post(lyrics_create, vocal_file_path, accompaniment_file_path, async_req=True)
        >>> result = thread.get()

        :param lyrics_create: (required)
        :type lyrics_create: LyricsCreate
        :param vocal_file_path:
        :type vocal_file_path: str
        :param accompaniment_file_path:
        :type accompaniment_file_path: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LyricsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_lyrics_lyrics_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.create_lyrics_lyrics_post_with_http_info(lyrics_create, vocal_file_path, accompaniment_file_path, **kwargs)  # noqa: E501

    @validate_arguments
    def create_lyrics_lyrics_post_with_http_info(self, lyrics_create : LyricsCreate, vocal_file_path : Optional[StrictStr] = None, accompaniment_file_path : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Lyrics  # noqa: E501

        Create a new lyrics entry with optional vocal and accompaniment audio files.  Accepts multipart/form-data. Text fields are form fields; files are uploaded to MinIO. Files are stored with deterministic paths based on the lyrics ID.  - vocal_file: Optional vocal track audio file (e.g., MP3, WAV) - accompaniment_file: Optional accompaniment/ instrumental track  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_lyrics_lyrics_post_with_http_info(lyrics_create, vocal_file_path, accompaniment_file_path, async_req=True)
        >>> result = thread.get()

        :param lyrics_create: (required)
        :type lyrics_create: LyricsCreate
        :param vocal_file_path:
        :type vocal_file_path: str
        :param accompaniment_file_path:
        :type accompaniment_file_path: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LyricsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'lyrics_create',
            'vocal_file_path',
            'accompaniment_file_path'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_lyrics_lyrics_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['lyrics_create'] is not None:
            _form_params.append(('lyrics_create', _params['lyrics_create']))

        if _params['vocal_file_path'] is not None:
            _form_params.append(('vocal_file_path', _params['vocal_file_path']))

        if _params['accompaniment_file_path'] is not None:
            _form_params.append(('accompaniment_file_path', _params['accompaniment_file_path']))

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '201': "LyricsResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/lyrics/', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def delete_lyrics_lyrics_lyrics_id_delete(self, lyrics_id : StrictStr, **kwargs) -> object:  # noqa: E501
        """Delete Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_lyrics_lyrics_lyrics_id_delete(lyrics_id, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_lyrics_lyrics_lyrics_id_delete_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.delete_lyrics_lyrics_lyrics_id_delete_with_http_info(lyrics_id, **kwargs)  # noqa: E501

    @validate_arguments
    def delete_lyrics_lyrics_lyrics_id_delete_with_http_info(self, lyrics_id : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_lyrics_lyrics_lyrics_id_delete_with_http_info(lyrics_id, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'lyrics_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_lyrics_lyrics_lyrics_id_delete" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['lyrics_id'] is not None:
            _path_params['lyrics_id'] = _params['lyrics_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "object",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/lyrics/{lyrics_id}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_lyrics_lyrics_lyrics_id_get(self, lyrics_id : StrictStr, **kwargs) -> LyricsResponse:  # noqa: E501
        """Get Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_lyrics_lyrics_lyrics_id_get(lyrics_id, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LyricsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_lyrics_lyrics_lyrics_id_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_lyrics_lyrics_lyrics_id_get_with_http_info(lyrics_id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_lyrics_lyrics_lyrics_id_get_with_http_info(self, lyrics_id : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """Get Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_lyrics_lyrics_lyrics_id_get_with_http_info(lyrics_id, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LyricsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'lyrics_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_lyrics_lyrics_lyrics_id_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['lyrics_id'] is not None:
            _path_params['lyrics_id'] = _params['lyrics_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "LyricsResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/lyrics/{lyrics_id}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def search_lyrics_lyrics_search_all_get(self, query : Annotated[StrictStr, Field(..., description="Search query across lyrics and song metadata")], language : Annotated[Optional[StrictStr], Field(description="Optional language filter (e.g., 'en', 'es')")] = None, **kwargs) -> List[LyricsSearchResponse]:  # noqa: E501
        """Search Lyrics  # noqa: E501

        Advanced multi-field search across lyrics.  Searches across: - Full lyrics text (complete song lyrics) - Individual chunk text (specific lines/verses/choruses) - Language filter (optional)  Supports fuzzy matching for typos.  Example: /lyrics/search/all?query=hello&language=en  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search_lyrics_lyrics_search_all_get(query, language, async_req=True)
        >>> result = thread.get()

        :param query: Search query across lyrics and song metadata (required)
        :type query: str
        :param language: Optional language filter (e.g., 'en', 'es')
        :type language: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[LyricsSearchResponse]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the search_lyrics_lyrics_search_all_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.search_lyrics_lyrics_search_all_get_with_http_info(query, language, **kwargs)  # noqa: E501

    @validate_arguments
    def search_lyrics_lyrics_search_all_get_with_http_info(self, query : Annotated[StrictStr, Field(..., description="Search query across lyrics and song metadata")], language : Annotated[Optional[StrictStr], Field(description="Optional language filter (e.g., 'en', 'es')")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Search Lyrics  # noqa: E501

        Advanced multi-field search across lyrics.  Searches across: - Full lyrics text (complete song lyrics) - Individual chunk text (specific lines/verses/choruses) - Language filter (optional)  Supports fuzzy matching for typos.  Example: /lyrics/search/all?query=hello&language=en  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search_lyrics_lyrics_search_all_get_with_http_info(query, language, async_req=True)
        >>> result = thread.get()

        :param query: Search query across lyrics and song metadata (required)
        :type query: str
        :param language: Optional language filter (e.g., 'en', 'es')
        :type language: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[LyricsSearchResponse], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'query',
            'language'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_lyrics_lyrics_search_all_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('query') is not None:  # noqa: E501
            _query_params.append(('query', _params['query']))

        if _params.get('language') is not None:  # noqa: E501
            _query_params.append(('language', _params['language']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "List[LyricsSearchResponse]",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/lyrics/search/all', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def update_lyrics_lyrics_lyrics_id_put(self, lyrics_id : StrictStr, lyrics_create : LyricsUpdate, vocal_file_path : Optional[StrictStr] = None, accompaniment_file_path : Optional[StrictStr] = None, **kwargs) -> LyricsResponse:  # noqa: E501
        """Update Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_lyrics_lyrics_lyrics_id_put(lyrics_id, lyrics_create, vocal_file_path, accompaniment_file_path, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param lyrics_create: (required)
        :type lyrics_create: LyricsUpdate
        :param vocal_file_path:
        :type vocal_file_path: str
        :param accompaniment_file_path:
        :type accompaniment_file_path: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: LyricsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_lyrics_lyrics_lyrics_id_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.update_lyrics_lyrics_lyrics_id_put_with_http_info(lyrics_id, lyrics_create, vocal_file_path, accompaniment_file_path, **kwargs)  # noqa: E501

    @validate_arguments
    def update_lyrics_lyrics_lyrics_id_put_with_http_info(self, lyrics_id : StrictStr, lyrics_create : LyricsUpdate, vocal_file_path : Optional[StrictStr] = None, accompaniment_file_path : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Update Lyrics  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_lyrics_lyrics_lyrics_id_put_with_http_info(lyrics_id, lyrics_create, vocal_file_path, accompaniment_file_path, async_req=True)
        >>> result = thread.get()

        :param lyrics_id: (required)
        :type lyrics_id: str
        :param lyrics_create: (required)
        :type lyrics_create: LyricsUpdate
        :param vocal_file_path:
        :type vocal_file_path: str
        :param accompaniment_file_path:
        :type accompaniment_file_path: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(LyricsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'lyrics_id',
            'lyrics_create',
            'vocal_file_path',
            'accompaniment_file_path'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_lyrics_lyrics_lyrics_id_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['lyrics_id'] is not None:
            _path_params['lyrics_id'] = _params['lyrics_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['lyrics_create'] is not None:
            _form_params.append(('lyrics_create', _params['lyrics_create']))

        if _params['vocal_file_path'] is not None:
            _form_params.append(('vocal_file_path', _params['vocal_file_path']))

        if _params['accompaniment_file_path'] is not None:
            _form_params.append(('accompaniment_file_path', _params['accompaniment_file_path']))

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "LyricsResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/lyrics/{lyrics_id}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
