# coding: utf-8

# flake8: noqa

"""
    Karaoke-Inator Voice Separation

    AI-powered voice separation service that separates vocals from background music using advanced audio processing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "VoiceSeparationApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ErrorResponse",
    "HTTPValidationError",
    "LocationInner",
    "SeparateVoiceResponse",
    "ValidationError",
]

# import apis into sdk package
from voice_separation_client.api.health_api import HealthApi as HealthApi
from voice_separation_client.api.voice_separation_api import VoiceSeparationApi as VoiceSeparationApi
from voice_separation_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from voice_separation_client.api_response import ApiResponse as ApiResponse
from voice_separation_client.api_client import ApiClient as ApiClient
from voice_separation_client.configuration import Configuration as Configuration
from voice_separation_client.exceptions import OpenApiException as OpenApiException
from voice_separation_client.exceptions import ApiTypeError as ApiTypeError
from voice_separation_client.exceptions import ApiValueError as ApiValueError
from voice_separation_client.exceptions import ApiKeyError as ApiKeyError
from voice_separation_client.exceptions import ApiAttributeError as ApiAttributeError
from voice_separation_client.exceptions import ApiException as ApiException

# import models into sdk package
from voice_separation_client.models.error_response import ErrorResponse as ErrorResponse
from voice_separation_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from voice_separation_client.models.location_inner import LocationInner as LocationInner
from voice_separation_client.models.separate_voice_response import SeparateVoiceResponse as SeparateVoiceResponse
from voice_separation_client.models.validation_error import ValidationError as ValidationError

