# coding: utf-8

# flake8: noqa
"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from lyrics_client.models.chunk import Chunk
from lyrics_client.models.error_response import ErrorResponse
from lyrics_client.models.http_validation_error import HTTPValidationError
from lyrics_client.models.location_inner import LocationInner
from lyrics_client.models.lyrics_extraction_response import LyricsExtractionResponse
from lyrics_client.models.lyrics_with_timestamps_response import LyricsWithTimestampsResponse
from lyrics_client.models.validation_error import ValidationError

