# coding: utf-8

"""
    Karaoke-Inator Lyrics Extraction

    AI-powered lyrics extraction service using Whisper speech recognition to transcribe audio to text

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from lyrics_client.models.chunk import Chunk
from typing import Optional, Set
from typing_extensions import Self

class LyricsWithTimestampsResponse(BaseModel):
    """
    Response model for lyrics extraction with timestamps.
    """ # noqa: E501
    text: StrictStr = Field(description="Full transcribed text")
    chunks: List[Chunk] = Field(description="List of lyrics segments with timestamps")
    total_duration_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    sample_rate: StrictInt = Field(description="Sample rate used for processing (Hz)")
    __properties: ClassVar[List[str]] = ["text", "chunks", "total_duration_seconds", "sample_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LyricsWithTimestampsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in chunks (list)
        _items = []
        if self.chunks:
            for _item_chunks in self.chunks:
                if _item_chunks:
                    _items.append(_item_chunks.to_dict())
            _dict['chunks'] = _items
        # set to None if total_duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.total_duration_seconds is None and "total_duration_seconds" in self.model_fields_set:
            _dict['total_duration_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LyricsWithTimestampsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "chunks": [Chunk.from_dict(_item) for _item in obj["chunks"]] if obj.get("chunks") is not None else None,
            "total_duration_seconds": obj.get("total_duration_seconds"),
            "sample_rate": obj.get("sample_rate")
        })
        return _obj


