apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otel-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "otel-collector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "otel-collector.fullname" . }}
      containers:
      - name: otel-collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
          - "--config=/etc/otel/config.yaml"
        ports:
        - name: otlp-grpc
          containerPort: {{ .Values.ports.otlp_grpc }}
          protocol: TCP
        - name: otlp-http
          containerPort: {{ .Values.ports.otlp_http }}
          protocol: TCP
        env:
        - name: GOGC
          value: "80"
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otel/config.yaml
          subPath: otel-collector-config.yaml
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: otel-collector-config
        configMap:
          name: {{ include "otel-collector.fullname" . }}-config
