apiVersion: v1
kind: Secret
metadata:
  name: kibana-admin-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.kibana.auth.username }}    # required field for kubernetes.io/basic-auth
  password: {{ .Values.kibana.auth.password }} # required field for kubernetes.io/basic-auth
  roles: superuser # optional, not part of kubernetes.io/basic-auth