/* tslint:disable */
/* eslint-disable */
/**
 * Karaoke-Inator Orchestrator
 * Master orchestration service for YouTube audio processing: voice separation and lyrics extraction
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Chunk {
    /**
     * Start time of the segment in seconds
     */
    'start': number;
    /**
     * End time of the segment in seconds
     */
    'end': number;
    /**
     * Lyrics text for this segment
     */
    'text': string;
}
export interface ConfidenceScore {
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface JobResponse {
    'job_id': string;
}
export interface LatestMessageResponse {
    'job_id': string;
    'message': ProcessingOutputMessage | null;
}
export interface LocationInner {
}
export interface Lyrics {
    'processing_id': string;
    'full_text': string;
    'chunks'?: Array<Chunk> | null;
    'language'?: string | null;
    'confidence_score'?: ConfidenceScore | null;
}
export interface PresignResponse {
    'url': string;
}
export interface ProcessingOutputMessage {
    'action'?: ProcessingOutputMessageActionEnum;
    'payload': ProcessingOutputPayload;
}

export const ProcessingOutputMessageActionEnum = {
    ProcessingOutput: 'processing_output'
} as const;

export type ProcessingOutputMessageActionEnum = typeof ProcessingOutputMessageActionEnum[keyof typeof ProcessingOutputMessageActionEnum];

export interface ProcessingOutputPayload {
    /**
     * Current step number (0-5)
     */
    'current_step': number;
    /**
     * Total number of steps
     */
    'total_steps'?: number;
    /**
     * Progress or status message
     */
    'desc': string;
    'result'?: ProcessingResult | null;
}
export interface ProcessingResponse {
    'youtube_url'?: string | null;
    'youtube_video_id'?: string | null;
    'title'?: string | null;
    'uploader'?: string | null;
    'uploader_url'?: string | null;
    'thumbnail_url'?: string | null;
    'thumbnail'?: string | null;
    'vocals_minio_path'?: string | null;
    'accompaniment_minio_path'?: string | null;
    'lyrics'?: Lyrics | null;
    'error_message'?: string | null;
    'id': string;
    'created_at'?: string | null;
}
export interface ProcessingResult {
    'success'?: boolean | null;
    'vocals_path'?: string | null;
    'accompaniment_path'?: string | null;
    'lyrics'?: string | null;
    'chunks'?: Array<Chunk> | null;
    'yt_metadata'?: YouTubeVideoMetadata | null;
    'error'?: string | null;
}
export interface QueuePositionResponse {
    'task_id': string;
    'position': number | null;
    'total_in_queue': number;
}
export interface SearchResultsResponse {
    'items': Array<ProcessingResponse>;
    'total': number;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
}
export interface YouTubeVideoMetadata {
    [key: string]: any;

    'id': string;
    'title': string;
    'uploader': string;
    'uploader_url': string;
    'thumbnail': string;
    'thumbnail_url': string;
    'description'?: string | null;
    'uploader_id'?: string | null;
    'duration'?: number | null;
    'view_count'?: number | null;
    'like_count'?: number | null;
    'dislike_count'?: number | null;
    'upload_date'?: string | null;
    'release_date'?: string | null;
    'categories'?: Array<string> | null;
    'tags'?: Array<string> | null;
    'age_limit'?: number | null;
    'is_live'?: boolean | null;
    'channel'?: string | null;
    'channel_id'?: string | null;
    'channel_url'?: string | null;
    'duration_string'?: string | null;
    'format_id'?: string | null;
    'format_note'?: string | null;
    'width'?: number | null;
    'height'?: number | null;
    'resolution'?: string | null;
    'fps'?: number | null;
    'vcodec'?: string | null;
    'acodec'?: string | null;
    'extent'?: string | null;
    'format'?: string | null;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Asyncapi Documentation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asyncapiDocumentationAsyncapiGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/asyncapi`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/html';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Asyncapi Specification
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asyncapiSpecificationAsyncapiJsonGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/asyncapi.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Openapi Yaml
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenapiYamlOpenapiYamlGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/openapi.yaml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Asyncapi Documentation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asyncapiDocumentationAsyncapiGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asyncapiDocumentationAsyncapiGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asyncapiDocumentationAsyncapiGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Asyncapi Specification
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async asyncapiSpecificationAsyncapiJsonGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.asyncapiSpecificationAsyncapiJsonGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.asyncapiSpecificationAsyncapiJsonGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Openapi Yaml
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOpenapiYamlOpenapiYamlGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOpenapiYamlOpenapiYamlGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getOpenapiYamlOpenapiYamlGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Asyncapi Documentation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asyncapiDocumentationAsyncapiGet(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.asyncapiDocumentationAsyncapiGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Asyncapi Specification
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        asyncapiSpecificationAsyncapiJsonGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.asyncapiSpecificationAsyncapiJsonGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Openapi Yaml
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenapiYamlOpenapiYamlGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getOpenapiYamlOpenapiYamlGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Asyncapi Documentation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asyncapiDocumentationAsyncapiGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asyncapiDocumentationAsyncapiGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Asyncapi Specification
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public asyncapiSpecificationAsyncapiJsonGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).asyncapiSpecificationAsyncapiJsonGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Openapi Yaml
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOpenapiYamlOpenapiYamlGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getOpenapiYamlOpenapiYamlGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Check if the lyrics extraction service is healthy and model is loaded
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Check if the lyrics extraction service is healthy and model is loaded
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Check if the lyrics extraction service is healthy and model is loaded
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * Check if the lyrics extraction service is healthy and model is loaded
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProcessingApi - axios parameter creator
 */
export const ProcessingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the latest message from a job\'s progress stream for reconnection
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestJobMessageProcessJobJobIdLatestMessageGet: async (jobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getLatestJobMessageProcessJobJobIdLatestMessageGet', 'jobId', jobId)
            const localVarPath = `/process/job/{job_id}/latest-message`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Processing Result By Id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingResultByIdProcessProcessingIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProcessingResultByIdProcessProcessingIdGet', 'id', id)
            const localVarPath = `/process/processing/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the position of a task in the Redis queue
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueuePositionProcessQueuePositionTaskIdGet: async (taskId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getQueuePositionProcessQueuePositionTaskIdGet', 'taskId', taskId)
            const localVarPath = `/process/queue/position/{task_id}`
                .replace(`{${"task_id"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Queue audio processing from YouTube URL
         * @param {string} youtubeUrl 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queueAudioProcessingProcessQueuePost: async (youtubeUrl: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'youtubeUrl' is not null or undefined
            assertParamExists('queueAudioProcessingProcessQueuePost', 'youtubeUrl', youtubeUrl)
            const localVarPath = `/process/queue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (youtubeUrl !== undefined) {
                localVarQueryParameter['youtube_url'] = youtubeUrl;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search processing results by lyrics query
         * @param {string} query 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchResultsByQueryProcessSearchGet: async (query: string, limit?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('searchResultsByQueryProcessSearchGet', 'query', query)
            const localVarPath = `/process/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProcessingApi - functional programming interface
 */
export const ProcessingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProcessingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get the latest message from a job\'s progress stream for reconnection
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LatestMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessingApi.getLatestJobMessageProcessJobJobIdLatestMessageGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Processing Result By Id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProcessingResultByIdProcessProcessingIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProcessingResultByIdProcessProcessingIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessingApi.getProcessingResultByIdProcessProcessingIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the position of a task in the Redis queue
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQueuePositionProcessQueuePositionTaskIdGet(taskId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueuePositionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQueuePositionProcessQueuePositionTaskIdGet(taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessingApi.getQueuePositionProcessQueuePositionTaskIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Queue audio processing from YouTube URL
         * @param {string} youtubeUrl 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queueAudioProcessingProcessQueuePost(youtubeUrl: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queueAudioProcessingProcessQueuePost(youtubeUrl, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessingApi.queueAudioProcessingProcessQueuePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search processing results by lyrics query
         * @param {string} query 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchResultsByQueryProcessSearchGet(query: string, limit?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchResultsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchResultsByQueryProcessSearchGet(query, limit, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProcessingApi.searchResultsByQueryProcessSearchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProcessingApi - factory interface
 */
export const ProcessingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProcessingApiFp(configuration)
    return {
        /**
         * 
         * @summary Get the latest message from a job\'s progress stream for reconnection
         * @param {string} jobId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId: string, options?: RawAxiosRequestConfig): AxiosPromise<LatestMessageResponse> {
            return localVarFp.getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Processing Result By Id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingResultByIdProcessProcessingIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ProcessingResponse> {
            return localVarFp.getProcessingResultByIdProcessProcessingIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the position of a task in the Redis queue
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQueuePositionProcessQueuePositionTaskIdGet(taskId: string, options?: RawAxiosRequestConfig): AxiosPromise<QueuePositionResponse> {
            return localVarFp.getQueuePositionProcessQueuePositionTaskIdGet(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Queue audio processing from YouTube URL
         * @param {string} youtubeUrl 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queueAudioProcessingProcessQueuePost(youtubeUrl: string, options?: RawAxiosRequestConfig): AxiosPromise<JobResponse> {
            return localVarFp.queueAudioProcessingProcessQueuePost(youtubeUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search processing results by lyrics query
         * @param {string} query 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchResultsByQueryProcessSearchGet(query: string, limit?: number, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<SearchResultsResponse> {
            return localVarFp.searchResultsByQueryProcessSearchGet(query, limit, page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProcessingApi - object-oriented interface
 */
export class ProcessingApi extends BaseAPI {
    /**
     * 
     * @summary Get the latest message from a job\'s progress stream for reconnection
     * @param {string} jobId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId: string, options?: RawAxiosRequestConfig) {
        return ProcessingApiFp(this.configuration).getLatestJobMessageProcessJobJobIdLatestMessageGet(jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Processing Result By Id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProcessingResultByIdProcessProcessingIdGet(id: string, options?: RawAxiosRequestConfig) {
        return ProcessingApiFp(this.configuration).getProcessingResultByIdProcessProcessingIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the position of a task in the Redis queue
     * @param {string} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQueuePositionProcessQueuePositionTaskIdGet(taskId: string, options?: RawAxiosRequestConfig) {
        return ProcessingApiFp(this.configuration).getQueuePositionProcessQueuePositionTaskIdGet(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Queue audio processing from YouTube URL
     * @param {string} youtubeUrl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public queueAudioProcessingProcessQueuePost(youtubeUrl: string, options?: RawAxiosRequestConfig) {
        return ProcessingApiFp(this.configuration).queueAudioProcessingProcessQueuePost(youtubeUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search processing results by lyrics query
     * @param {string} query 
     * @param {number} [limit] 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchResultsByQueryProcessSearchGet(query: string, limit?: number, page?: number, options?: RawAxiosRequestConfig) {
        return ProcessingApiFp(this.configuration).searchResultsByQueryProcessSearchGet(query, limit, page, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StorageApi - axios parameter creator
 */
export const StorageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a presigned URL for a file in the storage bucket
         * @summary Presign URL
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        presignUrlPresignGet: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('presignUrlPresignGet', 'key', key)
            const localVarPath = `/presign`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StorageApi - functional programming interface
 */
export const StorageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StorageApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a presigned URL for a file in the storage bucket
         * @summary Presign URL
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async presignUrlPresignGet(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresignResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.presignUrlPresignGet(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StorageApi.presignUrlPresignGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StorageApi - factory interface
 */
export const StorageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StorageApiFp(configuration)
    return {
        /**
         * Get a presigned URL for a file in the storage bucket
         * @summary Presign URL
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        presignUrlPresignGet(key: string, options?: RawAxiosRequestConfig): AxiosPromise<PresignResponse> {
            return localVarFp.presignUrlPresignGet(key, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StorageApi - object-oriented interface
 */
export class StorageApi extends BaseAPI {
    /**
     * Get a presigned URL for a file in the storage bucket
     * @summary Presign URL
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public presignUrlPresignGet(key: string, options?: RawAxiosRequestConfig) {
        return StorageApiFp(this.configuration).presignUrlPresignGet(key, options).then((request) => request(this.axios, this.basePath));
    }
}



