/* tslint:disable */
/* eslint-disable */
/**
 * Karaoke-Inator Orchestrator
 * Master orchestration service for YouTube audio processing: voice separation and lyrics extraction
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

