# coding: utf-8

"""
    Karaoke-Inator Voice Separation

    AI-powered voice separation service that separates vocals from background music using advanced audio processing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voice_separation_client.api.health_api import HealthApi  # noqa: E501


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health check  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
