# coding: utf-8

"""
    Karaoke-Inator Voice Separation

    AI-powered voice separation service that separates vocals from background music using advanced audio processing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voice_separation_client.models.separate_voice_response import SeparateVoiceResponse

class TestSeparateVoiceResponse(unittest.TestCase):
    """SeparateVoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeparateVoiceResponse:
        """Test SeparateVoiceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeparateVoiceResponse`
        """
        model = SeparateVoiceResponse()
        if include_optional:
            return SeparateVoiceResponse(
                vocals_path = '',
                accompaniment_path = ''
            )
        else:
            return SeparateVoiceResponse(
                vocals_path = '',
                accompaniment_path = '',
        )
        """

    def testSeparateVoiceResponse(self):
        """Test SeparateVoiceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
