# coding: utf-8

"""
    Karaoke-Inator Voice Separation

    AI-powered voice separation service that separates vocals from background music using advanced audio processing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voice_separation_client.api.voice_separation_api import VoiceSeparationApi  # noqa: E501


class TestVoiceSeparationApi(unittest.TestCase):
    """VoiceSeparationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VoiceSeparationApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_configuration_separate_voice_config_get(self) -> None:
        """Test case for get_configuration_separate_voice_config_get

        Get voice separation configuration  # noqa: E501
        """
        pass

    def test_separate_voice_unified_separate_voice_post(self) -> None:
        """Test case for separate_voice_unified_separate_voice_post

        Separate vocals from music  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
