# coding: utf-8

# flake8: noqa
"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from song_management_client.models.delete_response import DeleteResponse
from song_management_client.models.http_validation_error import HTTPValidationError
from song_management_client.models.location_inner import LocationInner
from song_management_client.models.lyrics_chunk import LyricsChunk
from song_management_client.models.lyrics_create import LyricsCreate
from song_management_client.models.lyrics_response import LyricsResponse
from song_management_client.models.lyrics_update import LyricsUpdate
from song_management_client.models.paginated_response_processing_result_response import PaginatedResponseProcessingResultResponse
from song_management_client.models.processing_result_create import ProcessingResultCreate
from song_management_client.models.processing_result_response import ProcessingResultResponse
from song_management_client.models.processing_result_update import ProcessingResultUpdate
from song_management_client.models.validation_error import ValidationError

