# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist
from song_management_client.models.lyrics_chunk import LyricsChunk

class LyricsSearchResponse(BaseModel):
    """
    Extended lyrics response for search results. Includes lyrics data and optional metadata about the source.  # noqa: E501
    """
    full_text: StrictStr = Field(default=..., description="Full lyrics text")
    chunks: Optional[conlist(LyricsChunk)] = Field(default=None, description="Lyrics chunks with timing")
    language: Optional[StrictStr] = Field(default='en', description="Language code")
    confidence_score: Optional[Union[StrictFloat, StrictInt]] = None
    title: Optional[StrictStr] = None
    creator: Optional[StrictStr] = None
    duration_seconds: Optional[StrictInt] = None
    thumbnail_url: Optional[StrictStr] = None
    id: StrictStr = Field(default=..., description="Lyrics ID")
    last_updated: Optional[datetime] = None
    __properties = ["full_text", "chunks", "language", "confidence_score", "title", "creator", "duration_seconds", "thumbnail_url", "id", "last_updated"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LyricsSearchResponse:
        """Create an instance of LyricsSearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in chunks (list)
        _items = []
        if self.chunks:
            for _item in self.chunks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['chunks'] = _items
        # set to None if confidence_score (nullable) is None
        # and __fields_set__ contains the field
        if self.confidence_score is None and "confidence_score" in self.__fields_set__:
            _dict['confidence_score'] = None

        # set to None if title (nullable) is None
        # and __fields_set__ contains the field
        if self.title is None and "title" in self.__fields_set__:
            _dict['title'] = None

        # set to None if creator (nullable) is None
        # and __fields_set__ contains the field
        if self.creator is None and "creator" in self.__fields_set__:
            _dict['creator'] = None

        # set to None if duration_seconds (nullable) is None
        # and __fields_set__ contains the field
        if self.duration_seconds is None and "duration_seconds" in self.__fields_set__:
            _dict['duration_seconds'] = None

        # set to None if thumbnail_url (nullable) is None
        # and __fields_set__ contains the field
        if self.thumbnail_url is None and "thumbnail_url" in self.__fields_set__:
            _dict['thumbnail_url'] = None

        # set to None if last_updated (nullable) is None
        # and __fields_set__ contains the field
        if self.last_updated is None and "last_updated" in self.__fields_set__:
            _dict['last_updated'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LyricsSearchResponse:
        """Create an instance of LyricsSearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LyricsSearchResponse.parse_obj(obj)

        _obj = LyricsSearchResponse.parse_obj({
            "full_text": obj.get("full_text"),
            "chunks": [LyricsChunk.from_dict(_item) for _item in obj.get("chunks")] if obj.get("chunks") is not None else None,
            "language": obj.get("language") if obj.get("language") is not None else 'en',
            "confidence_score": obj.get("confidence_score"),
            "title": obj.get("title"),
            "creator": obj.get("creator"),
            "duration_seconds": obj.get("duration_seconds"),
            "thumbnail_url": obj.get("thumbnail_url"),
            "id": obj.get("id"),
            "last_updated": obj.get("last_updated")
        })
        return _obj


