# coding: utf-8

# flake8: noqa
"""
    Karaoke-Inator Voice Separation

    AI-powered voice separation service that separates vocals from background music using advanced audio processing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from voice_separation_client.models.error_response import ErrorResponse
from voice_separation_client.models.http_validation_error import HTTPValidationError
from voice_separation_client.models.location_inner import LocationInner
from voice_separation_client.models.separate_voice_response import SeparateVoiceResponse
from voice_separation_client.models.validation_error import ValidationError

