# Lyrics Extraction Service Configuration

# model_size: "large-v3"
# model_size: "large-v3"
model_size: "medium"
compute_type: "int8"
# device: "cuda"
device: "cpu"

log_progress: false
word_timestamps: false
verbose: false
temperature: 0.0
vad: true
vad_threshold: 0.3

chunk_duration: 3000.0
overlap_duration: 10.0