# coding: utf-8

# flake8: noqa

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "ProcessingResultsApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "DeleteResponse",
    "HTTPValidationError",
    "LocationInner",
    "LyricsChunk",
    "LyricsCreate",
    "LyricsResponse",
    "LyricsUpdate",
    "PaginatedResponseProcessingResultResponse",
    "ProcessingResultCreate",
    "ProcessingResultResponse",
    "ProcessingResultUpdate",
    "ValidationError",
]

# import apis into sdk package
from song_management_client.api.health_api import HealthApi as HealthApi
from song_management_client.api.processing_results_api import ProcessingResultsApi as ProcessingResultsApi
from song_management_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from song_management_client.api_response import ApiResponse as ApiResponse
from song_management_client.api_client import ApiClient as ApiClient
from song_management_client.configuration import Configuration as Configuration
from song_management_client.exceptions import OpenApiException as OpenApiException
from song_management_client.exceptions import ApiTypeError as ApiTypeError
from song_management_client.exceptions import ApiValueError as ApiValueError
from song_management_client.exceptions import ApiKeyError as ApiKeyError
from song_management_client.exceptions import ApiAttributeError as ApiAttributeError
from song_management_client.exceptions import ApiException as ApiException

# import models into sdk package
from song_management_client.models.delete_response import DeleteResponse as DeleteResponse
from song_management_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from song_management_client.models.location_inner import LocationInner as LocationInner
from song_management_client.models.lyrics_chunk import LyricsChunk as LyricsChunk
from song_management_client.models.lyrics_create import LyricsCreate as LyricsCreate
from song_management_client.models.lyrics_response import LyricsResponse as LyricsResponse
from song_management_client.models.lyrics_update import LyricsUpdate as LyricsUpdate
from song_management_client.models.paginated_response_processing_result_response import PaginatedResponseProcessingResultResponse as PaginatedResponseProcessingResultResponse
from song_management_client.models.processing_result_create import ProcessingResultCreate as ProcessingResultCreate
from song_management_client.models.processing_result_response import ProcessingResultResponse as ProcessingResultResponse
from song_management_client.models.processing_result_update import ProcessingResultUpdate as ProcessingResultUpdate
from song_management_client.models.validation_error import ValidationError as ValidationError

