{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    {{- include "karaoke-inator.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.auth.rootUser | quote }}
  root-password: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}
