# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from song_management_client.models.lyrics_create import LyricsCreate  # noqa: E501

class TestLyricsCreate(unittest.TestCase):
    """LyricsCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LyricsCreate:
        """Test LyricsCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LyricsCreate`
        """
        model = LyricsCreate()  # noqa: E501
        if include_optional:
            return LyricsCreate(
                full_text = '',
                chunks = [
                    song_management_client.models.lyrics_chunk.LyricsChunk(
                        start = 1.337, 
                        end = 1.337, 
                        text = '', )
                    ],
                language = 'en',
                confidence_score = 1.337,
                title = '',
                creator = '',
                duration_seconds = 56,
                thumbnail_url = ''
            )
        else:
            return LyricsCreate(
                full_text = '',
        )
        """

    def testLyricsCreate(self):
        """Test LyricsCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
