# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from song_management_client.models.lyrics_chunk_input import LyricsChunkInput  # noqa: E501

class TestLyricsChunkInput(unittest.TestCase):
    """LyricsChunkInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LyricsChunkInput:
        """Test LyricsChunkInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LyricsChunkInput`
        """
        model = LyricsChunkInput()  # noqa: E501
        if include_optional:
            return LyricsChunkInput(
                start = 1.337,
                end = 1.337,
                text = ''
            )
        else:
            return LyricsChunkInput(
                start = 1.337,
                end = 1.337,
                text = '',
        )
        """

    def testLyricsChunkInput(self):
        """Test LyricsChunkInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
