# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from song_management_client.models.lyrics_search_response import LyricsSearchResponse  # noqa: E501

class TestLyricsSearchResponse(unittest.TestCase):
    """LyricsSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LyricsSearchResponse:
        """Test LyricsSearchResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LyricsSearchResponse`
        """
        model = LyricsSearchResponse()  # noqa: E501
        if include_optional:
            return LyricsSearchResponse(
                full_text = '',
                chunks = [
                    song_management_client.models.lyrics_chunk.LyricsChunk(
                        start = 1.337, 
                        end = 1.337, 
                        text = '', )
                    ],
                language = 'en',
                confidence_score = 1.337,
                title = '',
                creator = '',
                duration_seconds = 56,
                thumbnail_url = '',
                id = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return LyricsSearchResponse(
                full_text = '',
                id = '',
        )
        """

    def testLyricsSearchResponse(self):
        """Test LyricsSearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
