# coding: utf-8

"""
    Song Management Service

    CRUD API for managing songs, versions, processing results, and lyrics

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from song_management_client.api.lyrics_api import LyricsApi  # noqa: E501


class TestLyricsApi(unittest.TestCase):
    """LyricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LyricsApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_lyrics_lyrics_post(self) -> None:
        """Test case for create_lyrics_lyrics_post

        Create Lyrics  # noqa: E501
        """
        pass

    def test_delete_lyrics_lyrics_lyrics_id_delete(self) -> None:
        """Test case for delete_lyrics_lyrics_lyrics_id_delete

        Delete Lyrics  # noqa: E501
        """
        pass

    def test_get_lyrics_lyrics_lyrics_id_get(self) -> None:
        """Test case for get_lyrics_lyrics_lyrics_id_get

        Get Lyrics  # noqa: E501
        """
        pass

    def test_search_lyrics_lyrics_search_all_get(self) -> None:
        """Test case for search_lyrics_lyrics_search_all_get

        Search Lyrics  # noqa: E501
        """
        pass

    def test_update_lyrics_lyrics_lyrics_id_put(self) -> None:
        """Test case for update_lyrics_lyrics_lyrics_id_put

        Update Lyrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
