{{- if and .Values.image.auth.username .Values.image.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "karaoke-inator.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "karaoke-inator.dockerconfigjson" . | b64enc | quote }}
{{- end }}
